sudo: required

services:
- docker

arch:
  repos:
  packages:
  # pacman packages
  - make
  - python
  - python-virtualenv
  # aur packages
  script:
  - "make -f 'Makefile.ci' package && make -f 'Makefile.github' gh-pages"

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
