#!/bin/bash

set -euo pipefail

export ANSIBLE_USER_NAME="ansible"

apply_module()
{
  pacman \
    --sync \
    "ansible" \
    --noconfirm \
    --needed

  if ! is_user_created "${ANSIBLE_USER_NAME}"; then
    info "Creating ${ANSIBLE_USER_NAME} system user"
    useradd \
      --system \
      --shell "/usr/bin/nologin" \
      --groups "wheel" \
      --create-home \
      --home-dir "/var/lib/ansible" \
      "${ANSIBLE_USER_NAME}"
  fi
}
