#!/bin/bash

set -euo pipefail

export AUR_USER_NAME="aur"

apply_module()
{
  if ! is_user_created "${AUR_USER_NAME}"; then
    useradd \
      --system \
      --shell "/usr/bin/nologin" \
      --groups "wheel" \
      "${AUR_USER_NAME}"
  fi

  pacman \
    --sync \
    "base-devel" "git" "wget" \
    --noconfirm \
    --needed
}
