#!/bin/bash

apply_module()
{
  declare folder_path="${1}"

  sudo \
    --user="ansible" \
      ansible-playbook \
        -vvvv \
        --inventory="${folder_path}/inventory.ini" \
        "${folder_path}/playbook.yml" \
        --extra-vars "chroot=true"

}
