---
- name: disable IPv6
  sysctl:
    name: "net.ipv6.conf.all.disable_ipv6"
    value: "1"
    state: present
    sysctl_file: "/etc/sysctl.d/10-disable-ipv6.conf"
  notify: run systemd-sysctl
- name: setup network link
  copy:
    content: |
      [Match]
      MACAddress={{ network_iface_mac_address}}

      [Link]
      Name={{ network_iface_name }}
    dest: "/etc/systemd/network/50-{{ network_iface_name }}.link"
  notify: reload udev
- name: setup network
  copy:
    content: |
      [Match]
      Name={{ network_iface_name }}

      [Network]
      DHCP=yes
    dest: "/etc/systemd/network/{{ network_iface_name }}.network"
  notify: restart systemd-networkd
- name: install Avahi
  yay:
    name: "avahi"
    state: present
- name: start Avahi
  systemd:
    name: "avahi-daemon.service"
    state: started
    enabled: yes
- name: configure Avahi
  lineinfile:
    dest: "/etc/avahi/avahi-daemon.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
  - { regexp: "(# *)?use-ipv4=.*$", line: "use-ipv4=yes" }
  - { regexp: "(# *)?use-ipv6=.*$", line: "use-ipv6=no" }
  notify: reload Avahi
- name: add iptables rule
  copy:
    content: |
      -A INPUT -i {{ avahi_iface_name }} -p udp --dport {{ avahi_port }} -j ACCEPT
    dest: "/etc/iptables/iptables.rules.d/10-pulseaudio.conf"
  notify: restart iptables service
