- name: install packages
  yay:
    name: "nginx"
    state: present

- name: create folders
  file:
    path="{{ item }}"
    state=directory
  loop:
  - "/etc/nginx/sites.d"
  - "/etc/nginx/upstreams.d"

- name: configure
  copy:
    content: |
      worker_processes  1;
      events {
          worker_connections  1024;
      }

      http {
          include       mime.types;
          default_type  application/octet-stream;
          sendfile        on;
          keepalive_timeout  65;

          # Include upstreams
          include /etc/nginx/upstreams.d/*.conf;

          # Include sites
          include /etc/nginx/sites.d/*.conf;
      }
    dest: "/etc/nginx/nginx.conf"
  notify: reload nginx service

- name: add iptables rules
  copy:
    content: |
      -A INPUT -i en01 -p tcp --dport 80 -j ACCEPT
    dest: "/etc/iptables/iptables.rules.d/10-nginx.rules"
  notify: restart iptables service

- name: start nginx service
  systemd:
    name: "nginx"
    state: started
    enabled: yes
