---
- name: install nginx packages
  yay:
    name: "nginx"
    state: present
- name: add nginx site
  copy:
    content: |
      server {
          listen 80;
          server_name dtat.rouages.xyz;

          root   "/opt/DtaT";

          location / {
              autoindex on;
              auth_basic "Done to a Turn";
              auth_basic_user_file /etc/nginx/.htpasswd;
          }

          error_page   500 502 503 504  /50x.html;
          location = /50x.html {
              autoindex on;
          }
      }
    dest: "/etc/nginx/sites.d/10-dtat.conf"
  notify: reload nginx service
