---
- hosts: odroid-xu4
  become: yes
  vars:
    iface_name: "en01"
    iface_mac_address: "00:1e:06:30:90:0e"
  roles:
  - role: "bootstrap"
    vars:
      bootstrap_flavour: "odroid-xu4"
      bootstrap_iface_name: "{{ iface_name }}"
      bootstrap_iface_mac_address: "{{ iface_mac_address }}"
    tags:
    - "bootstrap"

  - role: "common"
    vars:
      common_iface_name: "{{ iface_name}}"
    tags:
    - "common"

  - role: "pulseaudio"
    vars:
      pulseaudio_iface_name: "{{ iface_name }}"
      pulseaudio_cards:
      - name: "alsa_card.usb-C-Media_Electronics_Inc._USB_Audio_Device-00"
        profile: "output:analog-stereo"
      - name: "alsa_card.platform-sound"
        profile: "off"
      pulseaudio_sinks:
      - name: "alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo"
        description: "ODroid-XU4"
    tags:
    - "audio"

#  - role: "storage-server"
#    vars:
#      storage_server_iface_name: "{{ iface_name }}"
#    tags:
#    - "data"

  - role: website-gear
  - role: website-dtat


- hosts: odroid-xu4
  become: yes
  tasks:
  - name: add iptables rules for SSH
    copy:
      content: |
        -A INPUT -i en01 -p tcp --dport 22 -j ACCEPT
      dest: "/etc/iptables/iptables.rules.d/10-ssh.rules"
  - name: restart iptables service
    systemd:
      name: "iptables.service"
      state: restarted
